### ISSUE TITLE
Provide a way to "conda env update" an environment: or more general conda commands.

### ISSUE THREAD

**Issue by mforbes** [theacodes/nox#346] opened 2020-09-08 07:53 UTC
**How would this feature be useful?**
Another common way of provisioning conda environments is through an `environment.yml` file which can be used to update an environment with

```bash
conda env update --file environment.yml
```

**Describe the solution you'd like**
Not sure what is ideal here.  This particular use-case could be solved by adding a command:

```python
    session.conda_env_update("environment.yml")
```

or similar.  This is easily implemented in [`session.py`](https://github.com/theacodes/nox/blob/master/nox/sessions.py):

```python
   ...
    def conda_env_update(self, envfile='environment.yml': str, **kwargs: Any) -> None:
        """Install invokes `conda env update`_ to update the session's
        environment.

        To install packages directly::

            session.conda_env_update('environment.yml')

        .. _conda env update:
        """
        venv = self._runner.venv

        prefix_args = ()  # type: Tuple[str, ...]
        if isinstance(venv, CondaEnv):
            prefix_args = ("--prefix", venv.location)
        elif not isinstance(venv, PassthroughEnv):  # pragma: no cover
            raise ValueError(
                "A session without a conda environment cannot update."
            )

        if "silent" not in kwargs:
            kwargs["silent"] = True

        self._run(
            "conda", "env", "update", *prefix_args, "--file", envfile, external="error", **kwargs
        )
   ...
```

however, it might be better to provide a more general fallback that allows users to customize commands for conda provisioning.

```python
    session.conda("env update --file environment.yml")
```

possibly with variables for the `--prefix` argument.  The other commands like `conda_install` could then be aliases to this more generic command.  Note: there are some differences between `conda install` and `conda env` command (for example, `--yes` is not supported by the latter) which [can cause confusion](https://github.com/conda/conda/issues/5253).

Related: one might also like to replace `conda` with [`mamba`](https://en.wikipedia.org/wiki/Mamba), so perhaps a kwarg could be provided.  I will play with this a bit and try to make a reasonable PR/

**Comment by smarie** [comment] 2020-09-08 15:36
Possible duplicate of #260 ?

**Comment by mforbes** [comment] 2020-09-08 18:24
Yes - it looks very similar.  Sorry, not sure how I missed that...  I will review what was discussed there, then merge my comments and discussion with that issue and then close this.

**Comment by bjlittle** [comment] 2020-11-03 03:07
@mforbes and @smarie I've just discovered `nox`, and it's really pretty awesome! Congratulations :100: :tada: 

I'd love to be able to create a conda environment based on an `environment.yml` so it would be great to know if this issue will mature into a pull-request?

**Comment by theacodes** [comment] 2020-11-19 16:56
Closing in favor of #260

**Closed by theacodes** 2020-11-19 16:56 UTC
Labels: enhancement
