### ISSUE TITLE
Allow use of venv rather than virtualenv

### ISSUE THREAD

**Issue by pfmoore** [theacodes/nox#199] opened 2019-05-26 19:20 UTC
**How would this feature be useful?**
Some projects (for example, `pipx`) have test suites that cannot run under virtualenv, but require venv. Being able to choose whether to use virtualenv or venv would allow using nox to run the test suite.

**Describe the solution you'd like**
The simplest solution I can think of is to use a parameter to `nox.session`, something like `@nox.session(stdlib_venv=True)`. But honestly, it doesn't matter much to me how it gets specified.

**Describe alternatives you've considered**
I can't really think of a good alternative, other than "use something else" :-( Ideally, `virtualenv` and `venv` would be sufficiently compatible that it doesn't matter which you use, but that simply doesn't seem to be the case.

**Comment by stsewd** [comment] 2019-05-26 20:22
`nox` is python3 only, so I guess we can just replace virtualenv?

**Comment by theacodes** [comment] 2019-05-26 20:28
No, unfortunately we still need it to create virtual environments for 2.7
sessions.

**Comment by pfmoore** [comment] 2019-05-26 22:27
... and there are things that only work in virtualenv (there are some nasty interactions if, for example, you create a venv from within a virtualenv). So I definitely think it's something where the user needs to be able to choose. Of course, as someone who wants to ditch Python 2.7 ASAP, my *personal* preference would be to go venv by default with an option to use virtualenv, but that would be backward incompatible, so I'm fine with venv being the one that needs to be opt-in.

**Comment by theacodes** [comment] 2019-05-28 00:03
Thinking of future-proofing this for `conda`, `pyenv`, or `pipenv` support as well (see #183 #4 #159) we should probably just extend the pattern we have with `ProcessEnv` and `VirtualEnv` to include `Venv`, `Conda and `PyEnv` backends as well. We could abstract a bit more common code of the current `VirtualEnv` class to make it the base for these new backends.

Session decorator wise, I think it makes the most sense to have something like:

```python
@nox.session(py="3.7", venv_backend="venv")
```

Thoughts?

**Comment by stsewd** [comment] 2019-05-28 00:22
I like the idea of having different backends, shouldn't be this a global option that could be overridden by each session?

**Comment by theacodes** [comment] 2019-05-28 00:36
I think per session alone makes the most sense, but happy to hear reasoning
for another global opt.

**Comment by cs01** [comment] 2019-07-28 15:46
I'm trying to migrate pipx's test suite to nox right now and am running into this issue. 

The problem is the pip executable is pointing to nox's rather than one that pipx created with venv:
```
>> ll /tmp/pipx_tests__fc881ve/subdir/pipxhome/.cache/3d7e26ae000b6c1/bin/python 
lrwxrwxrwx 1 csmith csmith 47 Jul 28 08:42 /tmp/pipx_tests__fc881ve/subdir/pipxhome/.cache/3d7e26ae000b6c1/bin/python -> /home/csmith/git/pipx/.nox/unittests/bin/python
```
Is there a workaround available in nox?

**Comment by cs01** [comment] 2019-07-28 16:00
To my surprise, I changed
```
        cmd = [sys.executable, "-m", "virtualenv", self.location]
```
to
```
        cmd = [sys.executable, "-m", "venv", self.location]
```
and nox still worked. The pipx tests then passed with nox. I'll see if I can put together a PR.

**Comment by cs01** [comment] 2019-07-29 00:44
I hacked something together, but I'll wait for https://github.com/theacodes/nox/pull/217/ to land before adding the venv backend.

**Comment by theacodes** [comment] 2019-08-01 03:14
Just merged #217, would love to see your changes! Let me know if you need help.

**Comment by theacodes** [comment] 2019-08-01 03:14
I've assigned this issue to you, @cs01, but definitely holler if you're not okay with that.

**Comment by cs01** [comment] 2019-08-01 03:22
No that's perfect. I think I am in a good spot to be assigned this since I got it working with pipx.

**Closed** 2019-08-12 02:00 UTC
Labels: enhancement, help wanted, in progress
