### ISSUE TITLE
Add property to determine if session has reused an existing virtual environment

### ISSUE THREAD

**Issue by PureFunctor** [theacodes/nox#429] opened 2021-05-26 03:13 UTC
**How would this feature be useful?**
Some complex workflows that require more expensive setups for sessions, [for example](<https://cjolowicz.github.io/posts/hypermodern-python-03-linting/>), would benefit if some steps can be skipped conditionally based on this property.

**Describe the solution you'd like**
This currently works for my use case: **Edit**: Assuming that `.nox` exists when `nox -r` is run.
```py
@nox.session
def lint(session):
    if not session._runner.global_config.reuse_existing_virtualenvs:
        ...  # Expensive install operations
    ...  # All other stuff
```
Perhaps adding a `reuse_existing_virtualenvs` property should alleviate verbosity/protected attribute access
```py
@nox.session
def lint(session):
    if not session.reuse_existing_virtualenvs:  # s/reuse/reusing/ ?
        ...  # Expensive install operations
    ...  # All other stuff
```
**Edit**: It's also probably best if (re)creation of virtual environments turns off this switch, as to resolve the condition in my workaround above.

**Describe alternatives you've considered**
I'd  say this seems to be the most straightforward solution.

**Comment by cjolowicz** [comment] 2021-05-26 13:40
Are you looking for a way to skip package installation when environments are reused?

In that case, this would be a duplicate of #394 .

**Comment by PureFunctor** [comment] 2021-05-26 14:34
Yes, a quick read-through tells me that I could use `run_always` and the new flag to skip installation steps, if I follow. Thanks and feel free to close this issue :slightly_smiling_face:

**Closed** 2021-05-27 14:57 UTC
