### ISSUE TITLE
Where did `session.virtualenv_dirname` go?

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#126] opened 2018-08-27 22:28 UTC
I.e. what is the equivalent feature in the new implementation?

**Comment by theacodes** [comment] 2018-08-28 01:09
Duplicate of https://github.com/theacodes/nox/issues/96, it's a missing feature but we at least have a rough idea of how to bring it back.

**Closed by theacodes** 2018-08-28 01:09 UTC
Labels: question
