### ISSUE TITLE
SIGINT handling: nox kills the process before it has a chance to finish cleaning up

### ISSUE THREAD

**Issue by Wenzel** [theacodes/nox#369] opened 2020-12-02 10:53 UTC
**Describe the bug**
When receiving a `SIGINT`, nox terminates the app immediately.
Therefore the app doesn't have a chance to cleanup, and the context managers release resource code are skipped. 

**How to reproduce**

Simple example
~~~
$ tree
.
├── foobar
│   ├── __main__.py
│   └── __pycache__
│       └── __main__.cpython-38.pyc
├── noxfile.py
└── __pycache__
    └── noxfile.cpython-38.pyc

3 directories, 4 files
~~~

`foobar/__main__.py`
~~~Python
import time
import os
from contextlib import contextmanager

@contextmanager
def foo(*args, **kwargs):
    print("acquire resource")
    try:
        yield {'foo': 'bar'}
    finally:
        print("releasing resource...")
        time.sleep(3)
        print("done releasing resource...")


with foo() as rsc:
    print(f"hello {rsc}")
    print(f"PID: os.getpid()")
    time.sleep(999)
~~~

`noxfile.py`
~~~Python
import nox

@nox.session()
def run(session):
    session.run("python", "-m", "foobar")
~~~

**demo without nox**
~~~
$ python3 -m foobar
acquire resource
hello {'foo': 'bar'}
PID: os.getpid()
^Creleasing resource...
done releasing resource...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wenzel/local/test_python/foobar/__main__.py", line 19, in <module>
    time.sleep(999)
KeyboardInterrupt
~~~
:arrow_up: here the context manager cleanup code has the time to execute, `done releasing resource` is printed`

**demo with nox**
~~~
$ nox -r -s run
nox > Running session run
nox > Re-using existing virtual environment at .nox/run.
nox > python -m foobar
acquire resource
hello {'foo': 'bar'}
PID: os.getpid()
^Creleasing resource...
nox > Interrupted...
nox > Session run interrupted.
~~~
:arrow_up: here, nox doesn't let the app a chance to finish the cleanup, `done releasing resource` is not printed.

:arrow_right:  **This is a serious bug**, as it can lead to database inconsistencies, resources not being cleaned up, etc ...

Using `nox==2020.8.22`

Related: https://github.com/theacodes/nox/issues/139

**Comment by Wenzel** [comment] 2021-01-28 09:25
hello,

asking again on this issue, @theacodes if you wish to comment maybe ?
do you need a more detailed explanation of the problem ?

Thank you !

**Comment by theacodes** [comment] 2021-02-11 23:28
@Wenzel acknowledged. Please remember that this project is maintained solely by volunteers so we don't have any guaranteed response or resolution time.

This is a duplicate of #139.

**Closed by theacodes** 2021-02-11 23:28 UTC
Labels: bug, help wanted

**Comment by Wenzel** [comment] 2021-02-11 23:33
> Please remember that this project is maintained solely by volunteers so we don't have any guaranteed response or resolution time.

Sure, I didn't wanted to be perceived that way, just that this bug might have nasty consequences for your end users.

thank you for your time :pray:
